name: Deploy to Hugging Face

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install huggingface_hub
          git clone https://huggingface.co/spaces/Vaishnavi-30/Energy-optimization hf_space
          cp -r . hf_space
          cd hf_space
          git add .
          git commit -m "sync from github"
          git push https://Vaishnavi-30:$HF_TOKEN@huggingface.co/spaces/Vaishnavi-30/Energy-optimization main
